/* PROCEDURE Y SYS_REFCURSOR */
SET SERVEROUTPUT ON;

DROP TRIGGER TRG_ACTUALIZAR_STOCK

-- trae los datos del usuario del correo que se envia 

CREATE OR REPLACE PROCEDURE SP_FIND_BY_CORREO(P_CORREO IN VARCHAR2,P_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT id_usuario, nombre, correo, password_hash, activo
        FROM   usuario
        WHERE  correo = P_CORREO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;

-- PRUEBA
CREATE OR REPLACE PROCEDURE SP_FIND_BY_CORREO_B(P1_CORREO IN VARCHAR2)
AS
    DATOS SYS_REFCURSOR;
    id_usuario NUMBER;
    nombre VARCHAR2(120);
    correo VARCHAR2(190);
    password_hash VARCHAR2(255);
    activo NUMBER;
BEGIN
    SP_FIND_BY_CORREO(P1_CORREO,DATOS);
    LOOP
        FETCH DATOS INTO id_usuario, nombre, correo, password_hash, activo;
        EXIT WHEN DATOS%NOTFOUND;
            DBMS_OUTPUT.PUT_LINE(id_usuario || ' ' || nombre ||  ' ' || correo || ' ' || password_hash || ' ' || activo);
    END LOOP;    
END;

EXEC SP_FIND_BY_CORREO_B('vero@gmail.com');



--------------------------------------------------------------------------

/* REGEXP_LIKE */

--TABLA USUARIO
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    correo VARCHAR2(190) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_correo CHECK (
        REGEXP_LIKE(correo,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    )
);


--------------------------------------------------------------------------


/* TRIGGER Y EXCEPTION */
-- modifica el stock despues de la compra 

CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_STOCK
AFTER INSERT ON detalle_pedido
FOR EACH ROW
BEGIN
    UPDATE producto
    SET stock = stock - :NEW.cantidad,fecha_modificacion = SYSTIMESTAMP
    WHERE id_producto = :NEW.id_producto;
    IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Producto no encontrado: ' || :NEW.id_producto);
    END IF;
END;



--Prueba
/* SELECT ID_PRODUCTO, STOCK, PRECIO
FROM PRODUCTO; */
/* 1	10	3000 */


/* insert into pedido (ID_USUARIO, FECHA, TOTAL, METODO_PAGO, ESTADO) VALUES (1, SYSTIMESTAMP, 15000, 'TARJETA', 'pendiente');
SELECT * FROM PEDIDO; */
/* 1	1	12/04/26 02:06:47,958000000 PM	15000	TARJETA	pendiente */


/* insert into detalle_pedido (CANTIDAD, PRECIO_UNITARIO, ID_PEDIDO, ID_PRODUCTO) VALUES (5,3000,1,1);
 */
/* SELECT ID_PRODUCTO, STOCK, PRECIO */
/* FROM PRODUCTO; */
/* 1	5	3000 */


--------------------------------------------------------------------------

/* FUNCTION */

-- FN PARA CONOCER LA FECHA DE ENTREGA DE UN REGISTRO EN LA TABLA PEDIDO_PERSONALIZADO

CREATE OR REPLACE FUNCTION FN_FECHA_ENTREGA(VID_PEDIDO IN NUMBER)
RETURN TIMESTAMP
AS
    VFECHA TIMESTAMP;
BEGIN
    SELECT fecha_entrega
    INTO VFECHA
    FROM pedido_personalizado
    WHERE id_pedido = VID_PEDIDO;

    RETURN VFECHA;

END;

-- COMANDOS DE PRUEBA
SELECT FN_FECHA_ENTREGA(1) FROM DUAL;

--------------------------------------------------------------------------


/* PACKAGE */


CREATE OR REPLACE PACKAGE PKG_RESENA 
AS
    PROCEDURE SP_INSERTAR_RESENA(VID_PRODUCTO NUMBER,
                                 VID_USUARIO NUMBER,
                                 VID_PEDIDO NUMBER,
                                 VCALIFICACION NUMBER,
                                 VCOMENTARIO CLOB);
                                 
    PROCEDURE SP_OBTENER_RESENA(VRESENA_ID NUMBER);

    PROCEDURE SP_ACTUALIZAR_RESENA(VRESENA_ID NUMBER,
                                   VCALIFICACION NUMBER,
                                   VCOMENTARIO CLOB,
                                   VAPROBADA NUMBER);

    PROCEDURE SP_DESAPROBAR_RESENA(VRESENA_ID NUMBER);

END PKG_RESENA;

--- BODY DEL PAQUETE
CREATE OR REPLACE PACKAGE BODY PKG_RESENA
AS
-------------- SP_INSERTAR_RESENA -------------- 
PROCEDURE SP_INSERTAR_RESENA(VID_PRODUCTO NUMBER,
                             VID_USUARIO NUMBER,
                             VID_PEDIDO NUMBER,
                             VCALIFICACION NUMBER,
                             VCOMENTARIO CLOB) AS
    BEGIN
    INSERT INTO resena (id_producto,
                        id_usuario,
                        id_pedido,
                        calificacion,
                        comentario,
                        aprobada,
                        fecha_creacion,
                        fecha_modificacion)
    VALUES (VID_PRODUCTO,
            VID_USUARIO,
            VID_PEDIDO,
            VCALIFICACION,
            VCOMENTARIO,
            1,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END SP_INSERTAR_RESENA;
-------------- SP_OBTENER_RESENA ---------------
PROCEDURE SP_OBTENER_RESENA(VRESENA_ID NUMBER)
AS
    VPRODUCTO resena.id_producto%TYPE;
    VUSUARIO resena.id_usuario%TYPE;
    VCALIFICACION resena.calificacion%TYPE;
    VAPROBADA resena.aprobada%TYPE;
BEGIN
    SELECT id_producto, id_usuario, calificacion, aprobada
    INTO VPRODUCTO, VUSUARIO, VCALIFICACION, VAPROBADA
    FROM resena
    WHERE id_resena = VRESENA_ID;
    DBMS_OUTPUT.PUT_LINE('ID RESENA: ' || VRESENA_ID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('ID USUARIO: ' || VUSUARIO);
    DBMS_OUTPUT.PUT_LINE('CALIFICACION: ' || VCALIFICACION);
    DBMS_OUTPUT.PUT_LINE('APROBADA: ' || VAPROBADA);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Resena no existe');
END SP_OBTENER_RESENA;
-------------- SP_ACTUALIZAR_RESENA ------------ 
PROCEDURE SP_ACTUALIZAR_RESENA(VRESENA_ID NUMBER,
                                                 VCALIFICACION NUMBER,
                                                 VCOMENTARIO CLOB,
                                                 VAPROBADA NUMBER) AS
    BEGIN
   UPDATE resena
    SET calificacion = VCALIFICACION,
        comentario = VCOMENTARIO,
        aprobada = VAPROBADA,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_resena = VRESENA_ID;
    COMMIT;
END SP_ACTUALIZAR_RESENA;
-------------- SP_DESAPROBAR_RESENA ------------
PROCEDURE SP_DESAPROBAR_RESENA(VRESENA_ID NUMBER)
AS
BEGIN
    UPDATE resena
    SET aprobada = 0,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_resena = VRESENA_ID;
    COMMIT;
END SP_DESAPROBAR_RESENA;

END PKG_RESENA;




--------------------------------------------------------------------------

/* SEQUENCE */


CREATE SEQUENCE SEQ_AUDITORIA_PEDIDO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE AUDITORIA_PEDIDO (
    id_auditoria NUMBER PRIMARY KEY,
    id_usuario NUMBER,
    producto VARCHAR2(40),
    fecha_registro TIMESTAMP DEFAULT SYSTIMESTAMP,
    tipo_pedido VARCHAR2(20), 
    id_pedido_ref NUMBER
);

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PEDIDO
AFTER INSERT OR UPDATE ON pedido
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_pedido (id_auditoria, id_usuario, producto, fecha_registro, tipo_pedido, id_pedido_ref)
    VALUES (seq_auditoria_pedido.NEXTVAL, :NEW.id_usuario, 'EN STOCK', SYSTIMESTAMP, 'NORMAL', :NEW.id_pedido);
END;

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_PEDIDO_PERSONALIZADO
AFTER INSERT OR UPDATE ON pedido_personalizado
FOR EACH ROW
BEGIN
    INSERT INTO auditoria_pedido (id_auditoria, id_usuario, producto, fecha_registro, tipo_pedido, id_pedido_ref)
    VALUES (seq_auditoria_pedido.NEXTVAL, :NEW.id_usuario, :NEW.producto, SYSTIMESTAMP, 'PERSONALIZADO', :NEW.id_pedido);
END;

SELECT * FROM AUDITORIA_PEDIDO;


SELECT * FROM PEDIDO;
INSERT INTO pedido (id_usuario, fecha, total, metodo_pago, estado)
VALUES (2, SYSTIMESTAMP,20000, 'TARJETA', 'pendiente');


SELECT * FROM PEDIDO_PERSONALIZADO;
INSERT INTO pedido_personalizado (
    producto, sabor_bizcocho, sabor_relleno,
    tamano, personalizacion, precio, estado,
    fecha_entrega, id_usuario, nombre_cliente, telefono, email
)
VALUES (
    'QUEQUE', 'CHOCOLATE', 'CHOCOLATE', 'GRANDE', 'SIN AZUCAR', 
    12000, 'en_proceso', SYSTIMESTAMP, 1, 'JOSE PEREZ', '88888888', 'jose@email.com'
);
--------------------------------------------------------------------------


/* SQL din�mico. */


--------------------------------------------------------------------------

/* cursor ?? */


