
-- 1. USUARIO (SCHEMA)
CREATE USER PASTELERIA IDENTIFIED BY "Pasteleria_MimisBakery";
GRANT CONNECT, RESOURCE TO PASTELERIA; -- Permisos del schema
ALTER SESSION SET CURRENT_SCHEMA = PASTELERIA; -- Usar el schema

-- 2. ROLES
CREATE ROLE rol_admin;
CREATE ROLE rol_operador;
CREATE ROLE rol_reportes;

-- 3. PERMISOS A ROLES
GRANT ALL PRIVILEGES TO rol_admin; -- ADMIN tiene acceso total 

-- 4. TRES USUARIOS COMO ADMIN
CREATE USER Nathalie IDENTIFIED BY "Nathalie123";
GRANT CONNECT TO Nathalie;
GRANT rol_admin TO Nathalie;

CREATE USER Leicel IDENTIFIED BY "Leicel123";
GRANT CONNECT TO Leicel;
GRANT rol_admin TO Leicel;

CREATE USER Erick IDENTIFIED BY "Erick123";
GRANT CONNECT TO Erick;
GRANT rol_admin TO Erick;

--TABLAS:
--TABLA USUARIO
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    correo VARCHAR2(190) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_correo CHECK (
        REGEXP_LIKE(correo,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    )
);

CREATE INDEX ix_usuario_correo ON usuario(correo);

-- 5. TOKEN CONTRASEÑA
CREATE TABLE expiracion_token_contraseña (
    id_token NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    codigo CHAR(6) NOT NULL,
    expira_en TIMESTAMP NOT NULL,
    usado NUMBER(1) DEFAULT 0 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_token_usuario 
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT chk_codigo 
        CHECK (REGEXP_LIKE(codigo, '^[0-9]{6}$'))
);

CREATE INDEX ix_token_usuario_codigo 
ON expiracion_token_contraseña(id_usuario, codigo, usado);

-- 6. PRODUCTO
CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(140) NOT NULL UNIQUE,
    descripcion CLOB,
    conservacion CLOB,
    precio NUMBER(10,2) DEFAULT 0 NOT NULL,
    stock NUMBER DEFAULT 0 NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_precio CHECK (precio >= 0),
    CONSTRAINT chk_stock CHECK (stock >= 0)
);

CREATE TABLE producto_tamano (
    id_tamano NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    etiqueta VARCHAR2(60) NOT NULL,
    CONSTRAINT fk_tamano_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_tamano_producto UNIQUE (id_producto, etiqueta)
);

CREATE TABLE producto_sabor (
    id_sabor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    etiqueta VARCHAR2(60) NOT NULL,
    CONSTRAINT fk_sabor_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_sabor_producto UNIQUE (id_producto, etiqueta)
);

CREATE TABLE producto_ingrediente (
    id_ingrediente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    nombre VARCHAR2(120) NOT NULL,
    CONSTRAINT fk_ing_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_ing_producto UNIQUE (id_producto, nombre)
);

CREATE TABLE opcion_pedido (
    id_opcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR2(50) NOT NULL,
    valor VARCHAR2(120) NOT NULL,
    descripcion CLOB,
    precio_adicional NUMBER(10,2) DEFAULT 0 NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_opcion UNIQUE(categoria, valor)
);

CREATE INDEX ix_opcion_categoria_activo 
ON opcion_pedido(categoria, activo);

CREATE TABLE pedido_personalizado (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto VARCHAR2(120) NOT NULL,
    sabor_bizcocho VARCHAR2(120) NOT NULL,
    sabor_relleno VARCHAR2(120) NOT NULL,
    tamano VARCHAR2(120) NOT NULL,
    personalizacion CLOB,
    precio NUMBER(10,2) DEFAULT 0 NOT NULL,
    estado VARCHAR2(50) DEFAULT 'pendiente' NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_entrega TIMESTAMP,
    id_usuario NUMBER,
    nombre_cliente VARCHAR2(120) NOT NULL,
    telefono VARCHAR2(20) NOT NULL,
    email VARCHAR2(190) NOT NULL,
    CONSTRAINT fk_pp_usuario 
    FOREIGN KEY(id_usuario)
    REFERENCES usuario(id_usuario) ON DELETE SET NULL
);

CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,
    fecha TIMESTAMP,
    total NUMBER(10,2),
    metodo_pago VARCHAR2(255),
    estado VARCHAR2(100),
    CONSTRAINT fk_pedido_usuario 
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
);

CREATE TABLE detalle_pedido (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    id_pedido NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    CONSTRAINT fk_dp 
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT fk_dp2 
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE INDEX ix_opcion_pedido_categoria_activo 
ON opcion_pedido(categoria, activo);

CREATE INDEX ix_pedido_personalizado_email 
ON pedido_personalizado(email);

CREATE INDEX ix_pedido_personalizado_fecha_entrega 
ON pedido_personalizado(fecha_entrega);

-- 11. RESEÑA 
CREATE TABLE resena (
    id_resena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    id_pedido NUMBER,
    calificacion NUMBER NOT NULL CHECK(calificacion BETWEEN 1 AND 5),
    comentario CLOB NOT NULL,
    aprobada NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_resena_producto
    FOREIGN KEY(id_producto) 
    REFERENCES producto(id_producto) ON DELETE CASCADE,

    CONSTRAINT fk_resena_usuario
    FOREIGN KEY(id_usuario) 
    REFERENCES usuario(id_usuario) ON DELETE CASCADE,

    CONSTRAINT fk_resena_pedido
    FOREIGN KEY(id_pedido) 
    REFERENCES pedido(id_pedido) ON DELETE SET NULL,

    CONSTRAINT uq_resena_usuario_producto 
    UNIQUE(id_usuario, id_producto)
);

-- Índices 
CREATE INDEX ix_resena_producto 
ON resena(id_producto, aprobada);

CREATE INDEX ix_resena_usuario 
ON resena(id_usuario);

CREATE INDEX ix_resena_fecha 
ON resena(fecha_creacion);

SELECT 
    p.nombre AS producto,
    u.nombre AS cliente,
    r.calificacion,
    SUBSTR(r.comentario, 1, 50) AS comentario,
    TO_CHAR(r.fecha_creacion, 'DD/MM/YYYY') AS fecha
FROM resena r
JOIN producto p ON r.id_producto = p.id_producto
JOIN usuario u ON r.id_usuario = u.id_usuario
ORDER BY r.fecha_creacion DESC
FETCH FIRST 5 ROWS ONLY;
