SELECT * FROM expiracion_token_contraseña;
select * from usuario;
SELECT * FROM PRODUCTO;
SELECT * FROM PEDIDO_PERSONALIZADO;
SELECT * FROM AUDITORIA_PEDIDO
ORDER BY FECHA_REGISTRO DESC;

SELECT CURRENT_TIMESTAMP FROM DUAL;