SELECT * FROM PEDIDO
ORDER BY FECHA DESC;

SELECT * FROM RESENA
ORDER BY FECHA_CREACION DESC;

SELECT * from usuario
ORDER BY FECHA_CREACION DESC;

SELECT * FROM PEDIDO_PERSONALIZADO
ORDER BY FECHA_CREACION DESC;

SELECT * FROM AUDITORIA_PEDIDO
ORDER BY FECHA_REGISTRO DESC;





