SET SERVEROUTPUT ON;
SET VERIFY OFF;
------------------------------------------------------------ TABLA USUARIO ------------------------------------------------------------
CREATE TABLE usuario (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(120) NOT NULL,
    correo VARCHAR2(190) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_correo CHECK (
        REGEXP_LIKE(correo,'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
    )
);



---- SP PARA INSERTAR NUEVO USUARIO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_USUARIO(VNOMBRE VARCHAR2,
                                                VCORREO VARCHAR2,
                                                VCONTRASENA VARCHAR2)
AS
BEGIN
    INSERT INTO usuario (nombre,
                         correo,
                         password_hash,
                         activo,
                         fecha_creacion,
                         fecha_modificacion)
    VALUES (VNOMBRE,
            VCORREO,
            VCONTRASENA,
            1,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_USUARIO('JOUSTEEN', 'JOUS@EJEMPLO.COM', 'PRUEBA123');

SELECT * FROM usuario;



---- SP PARA OBTENER INFO DE UN USUARIO
CREATE OR REPLACE PROCEDURE SP_OBTENER_USUARIO(VUSER_ID NUMBER)
AS
    VNOMBRE usuario.nombre%TYPE;
    VCORREO usuario.correo%TYPE;
    VACTIVO usuario.activo%TYPE;
BEGIN
    SELECT nombre, correo, activo
    INTO VNOMBRE, VCORREO, VACTIVO
    FROM usuario
    WHERE id_usuario = VUSER_ID;
    
    DBMS_OUTPUT.PUT_LINE('ID: ' || VUSER_ID);
    DBMS_OUTPUT.PUT_LINE('Nombre: ' || VNOMBRE);
    DBMS_OUTPUT.PUT_LINE('Correo: ' || VCORREO);
    DBMS_OUTPUT.PUT_LINE('Activo: ' || VACTIVO);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Usuario no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_USUARIO(2);



---- SP PARA ACTUALIZAR UN USUARIO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_USUARIO(VUSER_ID NUMBER,
                                                  VNOMBRE VARCHAR2,
                                                  VCORREO VARCHAR2,
                                                  VCONTRASENA VARCHAR2)
AS
BEGIN
    UPDATE usuario
    SET nombre = VNOMBRE,
        correo = VCORREO,
        password_hash = VCONTRASENA,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_usuario = VUSER_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_USUARIO(1, 'Jousteen', 'jousteen@ejemplo.com', 'Prueba1234');

SELECT * FROM usuario;



---- SP PARA DESACTIVAR UN USUARIO
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_USUARIO(VUSER_ID NUMBER)
AS
BEGIN
    UPDATE usuario
    SET activo = 0,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_usuario = VUSER_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_DESACTIVAR_USUARIO(1);

SELECT * FROM usuario;



------------------------------------------------------------ TOKEN contraseña ------------------------------------------------------------
CREATE TABLE expiracion_token_contraseña (
    id_token NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    codigo CHAR(6) NOT NULL,
    expira_en TIMESTAMP NOT NULL,
    usado NUMBER(1) DEFAULT 0 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_token_usuario 
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE CASCADE,
    CONSTRAINT chk_codigo 
        CHECK (REGEXP_LIKE(codigo, '^[0-9]{6}$'))
);



---- SP PARA INSERTAR UN NUEVO TOKEN
CREATE OR REPLACE PROCEDURE SP_INSERTAR_TOKEN(VUSER_ID NUMBER,
                                              VCODIGO CHAR,
                                              VEXPIRA_EN TIMESTAMP)
AS
BEGIN
    INSERT INTO expiracion_token_contraseña (id_usuario,
                                            codigo,
                                            expira_en,
                                            usado,
                                            fecha_creacion,
                                            fecha_modificacion)
    VALUES (VUSER_ID,
            VCODIGO,
            VEXPIRA_EN,
            0,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_TOKEN(1, '123456', '10/04/27');

SELECT * FROM expiracion_token_contraseña;



---- SP PARA OBTENER INFO DE UN TOKEN
CREATE OR REPLACE PROCEDURE SP_OBTENER_TOKEN(VTOKEN_ID NUMBER)
AS
    VUSUARIO expiracion_token_contraseña.id_usuario%TYPE;
    VCODIGO expiracion_token_contraseña.codigo%TYPE;
    VEXPIRA expiracion_token_contraseña.expira_en%TYPE;
    VUSADO expiracion_token_contraseña.usado%TYPE;
BEGIN
    SELECT id_usuario, codigo, expira_en, usado
    INTO VUSUARIO, VCODIGO, VEXPIRA, VUSADO
    FROM expiracion_token_contraseña
    WHERE id_token = VTOKEN_ID;

    DBMS_OUTPUT.PUT_LINE('ID TOKEN: ' || VTOKEN_ID);
    DBMS_OUTPUT.PUT_LINE('ID USUARIO: ' || VUSUARIO);
    DBMS_OUTPUT.PUT_LINE('CODIGO: ' || VCODIGO);
    DBMS_OUTPUT.PUT_LINE('EXPIRA EN: ' || VEXPIRA);
    DBMS_OUTPUT.PUT_LINE('USADO: ' || VUSADO);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Token no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_TOKEN(2);



---- SP PARA ACTUALIZAR UN TOKEN
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_TOKEN(VTOKEN_ID NUMBER,
                                                VCODIGO CHAR,
                                                VEXPIRA_EN TIMESTAMP,
                                                VUSADO NUMBER)
AS
BEGIN
    UPDATE expiracion_token_contraseña
    SET codigo = VCODIGO,
        expira_en = VEXPIRA_EN,
        usado = VUSADO,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_token = VTOKEN_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_TOKEN(2, '987654', '11/04/28', 0);

SELECT * FROM expiracion_token_contraseña;



---- SP PARA ELIMINAR UN TOKEN
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TOKEN(VTOKEN_ID NUMBER)
AS
BEGIN
    UPDATE expiracion_token_contraseña
    SET usado = 1,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_token = VTOKEN_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_TOKEN(2);

SELECT * FROM expiracion_token_contraseña;



------------------------------------------------------------ PRODUCTO ------------------------------------------------------------
CREATE TABLE producto (
    id_producto NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(140) NOT NULL UNIQUE,
    descripcion CLOB,
    conservacion CLOB,
    precio NUMBER(10,2) DEFAULT 0 NOT NULL,
    stock NUMBER DEFAULT 0 NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT chk_precio CHECK (precio >= 0),
    CONSTRAINT chk_stock CHECK (stock >= 0)
);


---- SP PARA INSERTAR NUEVO PRODUCTO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRODUCTO(VNOMBRE VARCHAR2,
                                                 VDESCRIPCION CLOB,
                                                 VCONSERVACION CLOB,
                                                 VPRECIO NUMBER,
                                                 VSTOCK NUMBER)
AS
BEGIN
    INSERT INTO producto (nombre,
                          descripcion,
                          conservacion,
                          precio,
                          stock,
                          activo,
                          fecha_creacion,
                          fecha_modificacion)
    VALUES (VNOMBRE,
            VDESCRIPCION,
            VCONSERVACION,
            VPRECIO,
            VSTOCK,
            1,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_PRODUCTO('PAN', 'DESCRIPCION DEL PAN', 'FRIO', 1500, 10);

SELECT * FROM producto;



---- SP PARA OBTENER INFO DE UN PRODUCTO
CREATE OR REPLACE PROCEDURE SP_OBTENER_PRODUCTO(VPRODUCTO_ID NUMBER)
AS
    VNOMBRE producto.nombre%TYPE;
    VDESCRIPCION producto.descripcion%TYPE;
    VPRECIO producto.precio%TYPE;
    VSTOCK producto.stock%TYPE;
    VACTIVO producto.activo%TYPE;
BEGIN
    SELECT nombre, descripcion, precio, stock, activo
    INTO VNOMBRE, VDESCRIPCION, VPRECIO, VSTOCK, VACTIVO
    FROM producto
    WHERE id_producto = VPRODUCTO_ID;

    DBMS_OUTPUT.PUT_LINE('ID: ' || VPRODUCTO_ID);
    DBMS_OUTPUT.PUT_LINE('Nombre: ' || VNOMBRE);
    DBMS_OUTPUT.PUT_LINE('Descripcion: ' || VDESCRIPCION);
    DBMS_OUTPUT.PUT_LINE('Precio: ' || VPRECIO);
    DBMS_OUTPUT.PUT_LINE('Stock: ' || VSTOCK);
    DBMS_OUTPUT.PUT_LINE('Activo: ' || VACTIVO);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Producto no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_PRODUCTO(1);



---- SP PARA ACTUALIZAR UN PRODUCTO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRODUCTO(VPRODUCTO_ID NUMBER,
                                                   VNOMBRE VARCHAR2,
                                                   VDESCRIPCION CLOB,
                                                   VCONSERVACION CLOB,
                                                   VPRECIO NUMBER,
                                                   VSTOCK NUMBER)
AS
BEGIN
    UPDATE producto
    SET nombre = VNOMBRE,
        descripcion = VDESCRIPCION,
        conservacion = VCONSERVACION,
        precio = VPRECIO,
        stock = VSTOCK,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_producto = VPRODUCTO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_PRODUCTO(1, 'PAN CUADRADO', 'PAN CORTADO EN CUADROS', 'TEMP AMBIENTE', 2000, 10);

SELECT * FROM producto;



---- SP PARA DESACTIVAR UN PRODUCTO
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PRODUCTO(VPRODUCTO_ID NUMBER)
AS
BEGIN
    UPDATE producto
    SET activo = 0,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_producto = VPRODUCTO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_PRODUCTO(1);

SELECT * FROM producto;



------------------------------------------------------------ PRODUCTO TAMANO ------------------------------------------------------------
CREATE TABLE producto_tamano (
    id_tamano NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    etiqueta VARCHAR2(60) NOT NULL,
    CONSTRAINT fk_tamano_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_tamano_producto UNIQUE (id_producto, etiqueta)
);



---- SP PARA INSERTAR NUEVO TAMANO PRODUCTO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_TAMANO(VID_PRODUCTO NUMBER,
                                               VETIQUETA VARCHAR2)
AS
BEGIN
    INSERT INTO producto_tamano (id_producto,
                                 etiqueta)
    VALUES (VID_PRODUCTO,
            VETIQUETA);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_TAMANO(1, 'GRANDE');

SELECT * FROM producto_tamano;



---- SP PARA OBTENER INFO DE TAMANO PRODUCTO
CREATE OR REPLACE PROCEDURE SP_OBTENER_TAMANO(VTAMANO_ID NUMBER)
AS
    VPRODUCTO producto_tamano.id_producto%TYPE;
    VETIQUETA producto_tamano.etiqueta%TYPE;
BEGIN
    SELECT id_producto, etiqueta
    INTO VPRODUCTO, VETIQUETA
    FROM producto_tamano
    WHERE id_tamano = VTAMANO_ID;

    DBMS_OUTPUT.PUT_LINE('ID TAMA�O: ' || VTAMANO_ID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('ETIQUETA: ' || VETIQUETA);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Tama�o no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_TAMANO(1);



---- SP PARA ACTUALIZAR UN TAMANO PRODUCTO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_TAMANO(VTAMANO_ID NUMBER,
                                                 VID_PRODUCTO NUMBER,
                                                 VETIQUETA VARCHAR2)
AS
BEGIN
    UPDATE producto_tamano
    SET id_producto = VID_PRODUCTO,
        etiqueta = VETIQUETA
    WHERE id_tamano = VTAMANO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_TAMANO(1, 1, 'MEDIANO');

SELECT * FROM producto_tamano;



---- SP PARA DESACTIVAR UN TAMANO PRODUCTO
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_TAMANO(VTAMANO_ID NUMBER)
AS
BEGIN
    UPDATE producto_tamano
    SET etiqueta = 'INACTIVO'
    WHERE id_tamano = VTAMANO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_TAMANO(2);

SELECT * FROM producto_tamano;



------------------------------------------------------------ PRODUCTO SABOR ------------------------------------------------------------
CREATE TABLE producto_sabor (
    id_sabor NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    etiqueta VARCHAR2(60) NOT NULL,
    CONSTRAINT fk_sabor_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_sabor_producto UNIQUE (id_producto, etiqueta)
);



---- SP PARA INSERTAR NUEVO PRODUCTO SABOR
CREATE OR REPLACE PROCEDURE SP_INSERTAR_SABOR(VID_PRODUCTO NUMBER,
                                              VETIQUETA VARCHAR2)
AS
BEGIN
    INSERT INTO producto_sabor (id_producto,
                                etiqueta)
    VALUES (VID_PRODUCTO,
            VETIQUETA);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_SABOR(1, 'CHOCOLATE');

SELECT * FROM producto_sabor;



---- SP PARA OBTENER INFO DE PRODUCTO SABOR
CREATE OR REPLACE PROCEDURE SP_OBTENER_SABOR(VSABOR_ID NUMBER)
AS
    VPRODUCTO producto_sabor.id_producto%TYPE;
    VETIQUETA producto_sabor.etiqueta%TYPE;
BEGIN
    SELECT id_producto, etiqueta
    INTO VPRODUCTO, VETIQUETA
    FROM producto_sabor
    WHERE id_sabor = VSABOR_ID;

    DBMS_OUTPUT.PUT_LINE('ID SABOR: ' || VSABOR_ID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('ETIQUETA: ' || VETIQUETA);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Sabor no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_SABOR(1);



---- SP PARA ACTUALIZAR UN PRODUCTO SABOR
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_SABOR(VSABOR_ID NUMBER,
                                                VID_PRODUCTO NUMBER,
                                                VETIQUETA VARCHAR2)
AS
BEGIN
    UPDATE producto_sabor
    SET id_producto = VID_PRODUCTO,
        etiqueta = VETIQUETA
    WHERE id_sabor = VSABOR_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_SABOR(1, 1, 'VAINILLA');

SELECT * FROM producto_sabor;



---- SP PARA DESACTIVAR UN PRODUCTO SABOR
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_SABOR(VSABOR_ID NUMBER)
AS
BEGIN
    UPDATE producto_sabor
    SET etiqueta = 'INACTIVO'
    WHERE id_sabor = VSABOR_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_SABOR(1);

SELECT * FROM producto_sabor;



------------------------------------------------------------ PRODUCTO INGREDIENTE ------------------------------------------------------------
CREATE TABLE producto_ingrediente (
    id_ingrediente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    nombre VARCHAR2(120) NOT NULL,
    CONSTRAINT fk_ing_producto FOREIGN KEY (id_producto)
    REFERENCES producto(id_producto) ON DELETE CASCADE,
    CONSTRAINT uq_ing_producto UNIQUE (id_producto, nombre)
);



---- SP PARA INSERTAR NUEVO PRODUCTO INGREDIENTE
CREATE OR REPLACE PROCEDURE SP_INSERTAR_INGREDIENTE(VID_PRODUCTO NUMBER,
                                                    VNOMBRE VARCHAR2)
AS
BEGIN
    INSERT INTO producto_ingrediente (id_producto,
                                     nombre)
    VALUES (VID_PRODUCTO,
            VNOMBRE);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_INGREDIENTE(1, 'AZUCAR');

SELECT * FROM producto_ingrediente;



---- SP PARA OBTENER INFO DE PRODUCTO INGREDIENTE
CREATE OR REPLACE PROCEDURE SP_OBTENER_INGREDIENTE(VINGREDIENTE_ID NUMBER)
AS
    VPRODUCTO producto_ingrediente.id_producto%TYPE;
    VNOMBRE producto_ingrediente.nombre%TYPE;
BEGIN
    SELECT id_producto, nombre
    INTO VPRODUCTO, VNOMBRE
    FROM producto_ingrediente
    WHERE id_ingrediente = VINGREDIENTE_ID;

    DBMS_OUTPUT.PUT_LINE('ID INGREDIENTE: ' || VINGREDIENTE_ID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('NOMBRE: ' || VNOMBRE);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Ingrediente no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_INGREDIENTE(1);



---- SP PARA ACTUALIZAR UN PRODUCTO INGREDIENTE
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_INGREDIENTE(VINGREDIENTE_ID NUMBER,
                                                      VID_PRODUCTO NUMBER,
                                                      VNOMBRE VARCHAR2)
AS
BEGIN
    UPDATE producto_ingrediente
    SET id_producto = VID_PRODUCTO,
        nombre = VNOMBRE
    WHERE id_ingrediente = VINGREDIENTE_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_INGREDIENTE(1, 1, 'HARINA');

SELECT * FROM producto_ingrediente;



---- SP PARA DESACTIVAR UN PRODUCTO INGREDIENTE
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_INGREDIENTE(VINGREDIENTE_ID NUMBER)
AS
BEGIN
    UPDATE producto_ingrediente
    SET nombre = 'INACTIVO'
    WHERE id_ingrediente = VINGREDIENTE_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_INGREDIENTE(1);

SELECT * FROM producto_ingrediente;



------------------------------------------------------------ OPCION PEDIDO ------------------------------------------------------------
CREATE TABLE opcion_pedido (
    id_opcion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria VARCHAR2(50) NOT NULL,
    valor VARCHAR2(120) NOT NULL,
    descripcion CLOB,
    precio_adicional NUMBER(10,2) DEFAULT 0 NOT NULL,
    activo NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT uq_opcion UNIQUE(categoria, valor)
);



---- SP PARA INSERTAR NUEVA OPCION PEDIDO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_OPCION(VCATEGORIA VARCHAR2,
                                               VVALOR VARCHAR2,
                                               VDESCRIPCION CLOB,
                                               VPRECIO_ADICIONAL NUMBER)
AS
BEGIN
    INSERT INTO opcion_pedido (categoria,
                              valor,
                              descripcion,
                              precio_adicional,
                              activo,
                              fecha_creacion,
                              fecha_modificacion)
    VALUES (VCATEGORIA,
            VVALOR,
            VDESCRIPCION,
            VPRECIO_ADICIONAL,
            1,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_OPCION('TAMANO', 'GRANDE', 'Tama�o grande', 500);

SELECT * FROM opcion_pedido;



---- SP PARA OBTENER INFO DE OPCION PEDIDO
CREATE OR REPLACE PROCEDURE SP_OBTENER_OPCION(VOPCION_ID NUMBER)
AS
    VCATEGORIA opcion_pedido.categoria%TYPE;
    VVALOR opcion_pedido.valor%TYPE;
    VPRECIO opcion_pedido.precio_adicional%TYPE;
    VACTIVO opcion_pedido.activo%TYPE;
BEGIN
    SELECT categoria, valor, precio_adicional, activo
    INTO VCATEGORIA, VVALOR, VPRECIO, VACTIVO
    FROM opcion_pedido
    WHERE id_opcion = VOPCION_ID;

    DBMS_OUTPUT.PUT_LINE('ID OPCION: ' || VOPCION_ID);
    DBMS_OUTPUT.PUT_LINE('CATEGORIA: ' || VCATEGORIA);
    DBMS_OUTPUT.PUT_LINE('VALOR: ' || VVALOR);
    DBMS_OUTPUT.PUT_LINE('PRECIO ADICIONAL: ' || VPRECIO);
    DBMS_OUTPUT.PUT_LINE('ACTIVO: ' || VACTIVO);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Opcion no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_OPCION(1);



---- SP PARA ACTUALIZAR OPCION PEDIDO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_OPCION(VOPCION_ID NUMBER,
                                                 VCATEGORIA VARCHAR2,
                                                 VVALOR VARCHAR2,
                                                 VDESCRIPCION CLOB,
                                                 VPRECIO_ADICIONAL NUMBER)
AS
BEGIN
    UPDATE opcion_pedido
    SET categoria = VCATEGORIA,
        valor = VVALOR,
        descripcion = VDESCRIPCION,
        precio_adicional = VPRECIO_ADICIONAL,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_opcion = VOPCION_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_OPCION(1, 'TAMANO', 'MEDIANO', 'Tama�o mediano', 300);

SELECT * FROM opcion_pedido;



---- SP PARA DESACTIVAR OPCION PEDIDO
CREATE OR REPLACE PROCEDURE SP_DESACTIVAR_OPCION(VOPCION_ID NUMBER)
AS
BEGIN
    UPDATE opcion_pedido
    SET activo = 0,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_opcion = VOPCION_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_DESACTIVAR_OPCION(1);

SELECT * FROM opcion_pedido;



------------------------------------------------------------ PEDIDO PERSONALIZADO ------------------------------------------------------------

---- SP PARA INSERTAR NUEVO PEDIDO PERSONALIZADO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PEDIDO(VPRODUCTO VARCHAR2,
                                               VSABOR_BIZCOCHO VARCHAR2,
                                               VSABOR_RELLENO VARCHAR2,
                                               VTAMANO VARCHAR2,
                                               VPERSONALIZACION CLOB,
                                               VPRECIO NUMBER,
                                               VESTADO VARCHAR2,
                                               VFECHA_ENTREGA TIMESTAMP,
                                               VID_USUARIO NUMBER,
                                               VNOMBRE_CLIENTE VARCHAR2,
                                               VTELEFONO VARCHAR2,
                                               VEMAIL VARCHAR2)
AS
BEGIN
    INSERT INTO pedido_personalizado (producto,
                                     sabor_bizcocho,
                                     sabor_relleno,
                                     tamano,
                                     personalizacion,
                                     precio,
                                     estado,
                                     fecha_creacion,
                                     fecha_entrega,
                                     id_usuario,
                                     nombre_cliente,
                                     telefono,
                                     email)
    VALUES (VPRODUCTO,
            VSABOR_BIZCOCHO,
            VSABOR_RELLENO,
            VTAMANO,
            VPERSONALIZACION,
            VPRECIO,
            VESTADO,
            SYSTIMESTAMP,
            VFECHA_ENTREGA,
            VID_USUARIO,
            VNOMBRE_CLIENTE,
            VTELEFONO,
            VEMAIL);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_PEDIDO('QUEQUE', 'CHOCOLATE', 'VAINILLA', 'GRANDE', 'CON MENSAJE', 15000, 'pendiente', SYSTIMESTAMP+2, 1, 'JUAN PEREZ', '88888888', 'juan@email.com');

SELECT * FROM pedido_personalizado;



---- SP PARA OBTENER INFO DE PEDIDO PERSONALIZADO
CREATE OR REPLACE PROCEDURE SP_OBTENER_PEDIDO(VPEDIDO_ID NUMBER)
AS
    VPRODUCTO pedido_personalizado.producto%TYPE;
    VPRECIO pedido_personalizado.precio%TYPE;
    VESTADO pedido_personalizado.estado%TYPE;
    VNOMBRE pedido_personalizado.nombre_cliente%TYPE;
BEGIN
    SELECT producto, precio, estado, nombre_cliente
    INTO VPRODUCTO, VPRECIO, VESTADO, VNOMBRE
    FROM pedido_personalizado
    WHERE id_pedido = VPEDIDO_ID;

    DBMS_OUTPUT.PUT_LINE('ID PEDIDO: ' || VPEDIDO_ID);
    DBMS_OUTPUT.PUT_LINE('PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('PRECIO: ' || VPRECIO);
    DBMS_OUTPUT.PUT_LINE('ESTADO: ' || VESTADO);
    DBMS_OUTPUT.PUT_LINE('CLIENTE: ' || VNOMBRE);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Pedido no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_PEDIDO(1);



---- SP PARA ACTUALIZAR UN PEDIDO PERSONALIZADO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PEDIDO(VPEDIDO_ID NUMBER,
                                                 VPRODUCTO VARCHAR2,
                                                 VSABOR_BIZCOCHO VARCHAR2,
                                                 VSABOR_RELLENO VARCHAR2,
                                                 VTAMANO VARCHAR2,
                                                 VPERSONALIZACION CLOB,
                                                 VPRECIO NUMBER,
                                                 VESTADO VARCHAR2,
                                                 VFECHA_ENTREGA TIMESTAMP,
                                                 VID_USUARIO NUMBER,
                                                 VNOMBRE_CLIENTE VARCHAR2,
                                                 VTELEFONO VARCHAR2,
                                                 VEMAIL VARCHAR2)
AS
BEGIN
    UPDATE pedido_personalizado
    SET producto = VPRODUCTO,
        sabor_bizcocho = VSABOR_BIZCOCHO,
        sabor_relleno = VSABOR_RELLENO,
        tamano = VTAMANO,
        personalizacion = VPERSONALIZACION,
        precio = VPRECIO,
        estado = VESTADO,
        fecha_entrega = VFECHA_ENTREGA,
        id_usuario = VID_USUARIO,
        nombre_cliente = VNOMBRE_CLIENTE,
        telefono = VTELEFONO,
        email = VEMAIL
    WHERE id_pedido = VPEDIDO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_PEDIDO(1, 'QUEQUE', 'FRESA', 'CHOCOLATE', 'MEDIANO', 'SIN AZUCAR', 12000, 'en_proceso', SYSTIMESTAMP+3, 1, 'JUAN PEREZ', '88888888', 'juan@email.com');

SELECT * FROM pedido_personalizado;



---- SP PARA DESACTIVAR UN PEDIDO PERSONALIZADO
CREATE OR REPLACE PROCEDURE SP_CANCELAR_PEDIDO(VPEDIDO_ID NUMBER)
AS
BEGIN
    UPDATE pedido_personalizado
    SET estado = 'CANCELADO'
    WHERE id_pedido = VPEDIDO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_CANCELAR_PEDIDO(1);

SELECT * FROM pedido_personalizado;



------------------------------------------------------------ PEDIDO ------------------------------------------------------------
CREATE TABLE pedido (
    id_pedido NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER,
    fecha TIMESTAMP,
    total NUMBER(10,2),
    metodo_pago VARCHAR2(255),
    estado VARCHAR2(100),
    CONSTRAINT fk_pedido_usuario 
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
);



---- SP PARA INSERTAR NUEVO PEDIDO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PEDIDO(VID_USUARIO NUMBER,
                                               VFECHA TIMESTAMP,
                                               VTOTAL NUMBER,
                                               VMETODO_PAGO VARCHAR2,
                                               VESTADO VARCHAR2)
AS
BEGIN
    INSERT INTO pedido (id_usuario,
                        fecha,
                        total,
                        metodo_pago,
                        estado)
    VALUES (VID_USUARIO,
            VFECHA,
            VTOTAL,
            VMETODO_PAGO,
            VESTADO);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_PEDIDO(1, SYSTIMESTAMP, 25000, 'TARJETA', 'pendiente');

SELECT * FROM pedido;



---- SP PARA OBTENER INFO DE UN PEDIDO
CREATE OR REPLACE PROCEDURE SP_OBTENER_PEDIDO(VPEDIDO_ID NUMBER)
AS
    VUSUARIO pedido.id_usuario%TYPE;
    VFECHA pedido.fecha%TYPE;
    VTOTAL pedido.total%TYPE;
    VESTADO pedido.estado%TYPE;
BEGIN
    SELECT id_usuario, fecha, total, estado
    INTO VUSUARIO, VFECHA, VTOTAL, VESTADO
    FROM pedido
    WHERE id_pedido = VPEDIDO_ID;

    DBMS_OUTPUT.PUT_LINE('ID PEDIDO: ' || VPEDIDO_ID);
    DBMS_OUTPUT.PUT_LINE('ID USUARIO: ' || VUSUARIO);
    DBMS_OUTPUT.PUT_LINE('FECHA: ' || VFECHA);
    DBMS_OUTPUT.PUT_LINE('TOTAL: ' || VTOTAL);
    DBMS_OUTPUT.PUT_LINE('ESTADO: ' || VESTADO);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Pedido no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_PEDIDO(1);



---- SP PARA ACTUALIZAR UN PEDIDO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PEDIDO(VPEDIDO_ID NUMBER,
                                                 VID_USUARIO NUMBER,
                                                 VFECHA TIMESTAMP,
                                                 VTOTAL NUMBER,
                                                 VMETODO_PAGO VARCHAR2,
                                                 VESTADO VARCHAR2)
AS
BEGIN
    UPDATE pedido
    SET id_usuario = VID_USUARIO,
        fecha = VFECHA,
        total = VTOTAL,
        metodo_pago = VMETODO_PAGO,
        estado = VESTADO
    WHERE id_pedido = VPEDIDO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_PEDIDO(1, 1, SYSTIMESTAMP, 30000, 'EFECTIVO', 'pagado');

SELECT * FROM pedido;



---- SP PARA DESACTIVAR UN PEDIDO
CREATE OR REPLACE PROCEDURE SP_CANCELAR_PEDIDO(VPEDIDO_ID NUMBER)
AS
BEGIN
    UPDATE pedido
    SET estado = 'CANCELADO'
    WHERE id_pedido = VPEDIDO_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_CANCELAR_PEDIDO(1);

SELECT * FROM pedido;



------------------------------------------------------------ DETALLE PEDIDO ------------------------------------------------------------
CREATE TABLE detalle_pedido (
    id_detalle NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cantidad NUMBER NOT NULL,
    precio_unitario NUMBER(10,2) NOT NULL,
    id_pedido NUMBER NOT NULL,
    id_producto NUMBER NOT NULL,
    CONSTRAINT fk_dp 
    FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
    CONSTRAINT fk_dp2 
    FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);



---- SP PARA INSERTAR NUEVO DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE SP_INSERTAR_DETALLE_PEDIDO(VCANTIDAD NUMBER,
                                                       VPRECIO_UNITARIO NUMBER,
                                                       VID_PEDIDO NUMBER,
                                                       VID_PRODUCTO NUMBER)
AS
BEGIN
    INSERT INTO detalle_pedido (cantidad,
                                precio_unitario,
                                id_pedido,
                                id_producto)
    VALUES (VCANTIDAD,
            VPRECIO_UNITARIO,
            VID_PEDIDO,
            VID_PRODUCTO);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_DETALLE_PEDIDO(2, 5000, 1, 1);

SELECT * FROM detalle_pedido;



---- SP PARA OBTENER INFO DE UN DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE SP_OBTENER_DETALLE_PEDIDO(VDETALLE_ID NUMBER)
AS
    VCANTIDAD detalle_pedido.cantidad%TYPE;
    VPRECIO detalle_pedido.precio_unitario%TYPE;
    VPID detalle_pedido.id_pedido%TYPE;
    VPROD detalle_pedido.id_producto%TYPE;
BEGIN
    SELECT cantidad, precio_unitario, id_pedido, id_producto
    INTO VCANTIDAD, VPRECIO, VPID, VPROD
    FROM detalle_pedido
    WHERE id_detalle = VDETALLE_ID;

    DBMS_OUTPUT.PUT_LINE('ID DETALLE: ' || VDETALLE_ID);
    DBMS_OUTPUT.PUT_LINE('CANTIDAD: ' || VCANTIDAD);
    DBMS_OUTPUT.PUT_LINE('PRECIO UNITARIO: ' || VPRECIO);
    DBMS_OUTPUT.PUT_LINE('ID PEDIDO: ' || VPID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPROD);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Detalle no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_DETALLE_PEDIDO(1);



---- SP PARA ACTUALIZAR UN DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_DETALLE_PEDIDO(VDETALLE_ID NUMBER,
                                                         VCANTIDAD NUMBER,
                                                         VPRECIO_UNITARIO NUMBER,
                                                         VID_PEDIDO NUMBER,
                                                         VID_PRODUCTO NUMBER)
AS
BEGIN
    UPDATE detalle_pedido
    SET cantidad = VCANTIDAD,
        precio_unitario = VPRECIO_UNITARIO,
        id_pedido = VID_PEDIDO,
        id_producto = VID_PRODUCTO
    WHERE id_detalle = VDETALLE_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_DETALLE_PEDIDO(1, 3, 5500, 1, 1);

SELECT * FROM detalle_pedido;



---- SP PARA DESACTIVAR UN DETALLE PEDIDO
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_DETALLE_PEDIDO(VDETALLE_ID NUMBER)
AS
BEGIN
    DELETE FROM detalle_pedido
    WHERE id_detalle = VDETALLE_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ELIMINAR_DETALLE_PEDIDO(1);

SELECT * FROM detalle_pedido;



------------------------------------------------------------ RESE�A ------------------------------------------------------------
CREATE TABLE resena (
    id_resena NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto NUMBER NOT NULL,
    id_usuario NUMBER NOT NULL,
    id_pedido NUMBER,
    calificacion NUMBER NOT NULL CHECK(calificacion BETWEEN 1 AND 5),
    comentario CLOB NOT NULL,
    aprobada NUMBER(1) DEFAULT 1 NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT SYSTIMESTAMP,
    fecha_modificacion TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT fk_resena_producto
    FOREIGN KEY(id_producto) 
    REFERENCES producto(id_producto) ON DELETE CASCADE,

    CONSTRAINT fk_resena_usuario
    FOREIGN KEY(id_usuario) 
    REFERENCES usuario(id_usuario) ON DELETE CASCADE,

    CONSTRAINT fk_resena_pedido
    FOREIGN KEY(id_pedido) 
    REFERENCES pedido(id_pedido) ON DELETE SET NULL,

    CONSTRAINT uq_resena_usuario_producto 
    UNIQUE(id_usuario, id_producto)
);



---- SP PARA INSERTAR NUEVA RESE�A
CREATE OR REPLACE PROCEDURE SP_INSERTAR_RESENA(VID_PRODUCTO NUMBER,
                                               VID_USUARIO NUMBER,
                                               VID_PEDIDO NUMBER,
                                               VCALIFICACION NUMBER,
                                               VCOMENTARIO CLOB)
AS
BEGIN
    INSERT INTO resena (id_producto,
                        id_usuario,
                        id_pedido,
                        calificacion,
                        comentario,
                        aprobada,
                        fecha_creacion,
                        fecha_modificacion)
    VALUES (VID_PRODUCTO,
            VID_USUARIO,
            VID_PEDIDO,
            VCALIFICACION,
            VCOMENTARIO,
            1,
            SYSTIMESTAMP,
            SYSTIMESTAMP);
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_INSERTAR_RESENA(1, 1, 1, 5, 'EXCELENTE PRODUCTO');

SELECT * FROM resena;



---- SP PARA OBTENER INFO DE UNA RESE�A
CREATE OR REPLACE PROCEDURE SP_OBTENER_RESENA(VRESENA_ID NUMBER)
AS
    VPRODUCTO resena.id_producto%TYPE;
    VUSUARIO resena.id_usuario%TYPE;
    VCALIFICACION resena.calificacion%TYPE;
    VAPROBADA resena.aprobada%TYPE;
BEGIN
    SELECT id_producto, id_usuario, calificacion, aprobada
    INTO VPRODUCTO, VUSUARIO, VCALIFICACION, VAPROBADA
    FROM resena
    WHERE id_resena = VRESENA_ID;

    DBMS_OUTPUT.PUT_LINE('ID RESENA: ' || VRESENA_ID);
    DBMS_OUTPUT.PUT_LINE('ID PRODUCTO: ' || VPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('ID USUARIO: ' || VUSUARIO);
    DBMS_OUTPUT.PUT_LINE('CALIFICACION: ' || VCALIFICACION);
    DBMS_OUTPUT.PUT_LINE('APROBADA: ' || VAPROBADA);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('Resena no existe');
END;

-- COMANDOS DE PRUEBA
EXEC SP_OBTENER_RESENA(1);



---- SP PARA ACTUALIZAR UNA RESE�A
CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_RESENA(VRESENA_ID NUMBER,
                                                 VCALIFICACION NUMBER,
                                                 VCOMENTARIO CLOB,
                                                 VAPROBADA NUMBER)
AS
BEGIN
    UPDATE resena
    SET calificacion = VCALIFICACION,
        comentario = VCOMENTARIO,
        aprobada = VAPROBADA,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_resena = VRESENA_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_ACTUALIZAR_RESENA(1, 4, 'MUY BUENO', 1);

SELECT * FROM resena;



---- SP PARA DESACTIVAR UNA RESE�A
CREATE OR REPLACE PROCEDURE SP_DESAPROBAR_RESENA(VRESENA_ID NUMBER)
AS
BEGIN
    UPDATE resena
    SET aprobada = 0,
        fecha_modificacion = SYSTIMESTAMP
    WHERE id_resena = VRESENA_ID;
    COMMIT;
END;

-- COMANDOS DE PRUEBA
EXEC SP_DESAPROBAR_RESENA(1);

SELECT * FROM resena;

--- PAQUETE PARA SPs DE TABLA RESE�A
CREATE OR REPLACE PACKAGE PKG_RESENA 
AS
    PROCEDURE SP_INSERTAR_RESENA(VID_PRODUCTO NUMBER,
                                 VID_USUARIO NUMBER,
                                 VID_PEDIDO NUMBER,
                                 VCALIFICACION NUMBER,
                                 VCOMENTARIO CLOB);
                                 
    PROCEDURE SP_OBTENER_RESENA(VRESENA_ID NUMBER);

    PROCEDURE SP_ACTUALIZAR_RESENA(VRESENA_ID NUMBER,
                                   VCALIFICACION NUMBER,
                                   VCOMENTARIO CLOB,
                                   VAPROBADA NUMBER);

    PROCEDURE SP_DESAPROBAR_RESENA(VRESENA_ID NUMBER);

END PKG_RESENA;

commit;


CREATE OR REPLACE PROCEDURE SP_OBTENER_PEDIDO(P_ID_PEDIDO IN NUMBER, P_CURSOR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT id_pedido, id_usuario, fecha, total, metodo_pago, estado
        FROM pedido
        WHERE id_pedido = P_ID_PEDIDO;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;

 
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PEDIDO(
    VMETODO_PAGO VARCHAR2,
    VTOTAL NUMBER,
    VESTADO VARCHAR2,
    VID_USUARIO NUMBER,
    VID_PEDIDO OUT NUMBER
)
AS
BEGIN
    INSERT INTO pedido (metodo_pago, total, estado, id_usuario, fecha)
    VALUES (VMETODO_PAGO, VTOTAL, VESTADO, VID_USUARIO, SYSTIMESTAMP)
    RETURNING id_pedido INTO VID_PEDIDO;
    COMMIT;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_RESENA_POR_ID(
    P_ID_RESENA IN NUMBER,
    P_CURSOR    OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT ID_RESENA, ID_PRODUCTO, ID_USUARIO, ID_PEDIDO,
               CALIFICACION, COMENTARIO, APROBADA,
               FECHA_CREACION, FECHA_MODIFICACION
        FROM   RESENA
        WHERE  ID_RESENA = P_ID_RESENA;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_RESENA_POR_ID(
    P_ID_RESENA IN NUMBER,
    P_CURSOR    OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN P_CURSOR FOR
        SELECT ID_RESENA, ID_PRODUCTO, ID_USUARIO, ID_PEDIDO,
               CALIFICACION, COMENTARIO, APROBADA,
               FECHA_CREACION, FECHA_MODIFICACION
        FROM   RESENA
        WHERE  ID_RESENA = P_ID_RESENA;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;